// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeOvg-tD9nkLQZAZoQHi5JyjQcPsK3MEg',
    appId: '1:191489861331:web:b9b3c935628718908ad626',
    messagingSenderId: '191489861331',
    projectId: 'videalpha-9e81b',
    authDomain: 'videalpha-9e81b.firebaseapp.com',
    storageBucket: 'videalpha-9e81b.appspot.com',
    measurementId: 'G-2ZKYBEPJJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5f1AZTUAtcenwB3IhMIrSkaUs208GAs8',
    appId: '1:191489861331:android:e09dc75a7883810f8ad626',
    messagingSenderId: '191489861331',
    projectId: 'videalpha-9e81b',
    storageBucket: 'videalpha-9e81b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPS3RWmCI9jCbG-16kSiRCa60NDXpOznI',
    appId: '1:191489861331:ios:965f473274adf4fe8ad626',
    messagingSenderId: '191489861331',
    projectId: 'videalpha-9e81b',
    storageBucket: 'videalpha-9e81b.appspot.com',
    iosClientId: '191489861331-ingiotqgi7t3eghka2blnb7mhg844erj.apps.googleusercontent.com',
    iosBundleId: 'com.example.videalphaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPS3RWmCI9jCbG-16kSiRCa60NDXpOznI',
    appId: '1:191489861331:ios:965f473274adf4fe8ad626',
    messagingSenderId: '191489861331',
    projectId: 'videalpha-9e81b',
    storageBucket: 'videalpha-9e81b.appspot.com',
    iosClientId: '191489861331-ingiotqgi7t3eghka2blnb7mhg844erj.apps.googleusercontent.com',
    iosBundleId: 'com.example.videalphaProject',
  );
}
